# Generated by Django 4.2 on 2023-10-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=120, verbose_name='密码'),
        ),
    ]
